### ISSUE TITLE
Enable Travis Build

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/FIB.jl#1]
Before we put this in the POMDPs package, we should enable automatic testing on Travis. This will help to catch errors before users find them, especially ones like forgetting dependencies that are harder to catch by just running tests on your own computer. Just click on the "build" badge in the README and follow the instructions.

**Comment by zsunberg** [comment]
Also, if other people contribute, this will automatically test all pull requests so you can see any errors before merging without running anything on your machine.

**Comment by zsunberg** [comment]
Also, please enable the code coverage reporting (the "coverage" badge) before we put FIB in the list of solvers. Thanks!

**Comment by mykelk** [comment]
I enabled Travis and Coveralls.

**Comment by zsunberg** [comment]
Thanks
